FROM ubuntu:22.04

USER root

RUN apt-get update
RUN apt-get -y install curl
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && apt-get -y install nodejs
RUN apt-get -y install npm
RUN npm install npm -g npm@latest
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
RUN source ~/.bashrc
RUN nvm install v18.12.0
RUN npm install -g @vue/cli

WORKDIR /frontend-q-sort
RUN mkdir node_modules
RUN npm install
